### ISSUE TITLE
Login Button `NoSuchMethodError` when correct credentials used

### ISSUE THREAD

**Issue by kondanta** [Egomination/quela#7]
Here's the log
```
I/flutter (28638): Signed in: 7tIHp[rest of the uuid]
I/flutter (28638): Error: NoSuchMethodError: The method 'markNeedsBuild' was called on null.
I/flutter (28638): Receiver: null
I/flutter (28638): Tried calling: markNeedsBuild()
E/flutter (28638): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: Class 'NoSuchMethodError' has no instance getter 'message'.
E/flutter (28638): Receiver: Instance of 'NoSuchMethodError'
E/flutter (28638): Tried calling: message
E/flutter (28638): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50)
E/flutter (28638): #1      _LoginFormState._submit.<anonymous closure> (package:quela/pages/login/login_form.dart:60)
E/flutter (28638): #2      State.setState (package:flutter/src/widgets/framework.dart:1122)
E/flutter (28638): #3      _LoginFormState._submit (package:quela/pages/login/login_form.dart:58)
E/flutter (28638): <asynchronous suspension>
E/flutter (28638): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513)
E/flutter (28638): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568)
E/flutter (28638): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120)
E/flutter (28638): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242)
E/flutter (28638): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204)
E/flutter (28638): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156)
E/flutter (28638): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218)
E/flutter (28638): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192)
E/flutter (28638): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149)
E/flutter (28638): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101)
E/flutter (28638): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85)
E/flutter (28638): #15     _rootRunUnary (dart:async/zone.dart:1136)
E/flutter (28638): #16     _CustomZone.runUnary (dart:async/zone.dart:1029)
E/flutter (28638): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
E/flutter (28638): #18     _invoke1 (dart:ui/hooks.dart:223)
E/flutter (28638): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:144)
E/flutter (28638):
```
It happens when you enter correct credentials your first try. It does not happen after an unsuccesfull authorization attempt.

**Comment by sasalx** [comment]
From the looks of it, this only happens on release mode. Also, it's important to note that this occurs because try catch is not working as expected. When the app successfully signs in, it still visits the catch part of the function. To be honest, I don't know why this is happening. This might be related to Firebase.

**Comment by kondanta** [comment]
As for reminder, we found that it was related to the setState function which was trying to run after the login page's disposed by the engine. I am expecting @sasalx  quick fix PR since we already fixed it on @sasalx PC.
